# This file and its quirks are documented here:
# https://github.com/aws/aws-sam-cli/blob/develop/docs/sam-config-docs.md
version = 0.1

####################################################################################
## NB: Don't insert a "default" profile in this file! ##############################
###### Only use named, per-environment profiles. ###################################
###### This will help guard against accidentally targetting the wrong environment. #
####################################################################################

[production]

[production.deploy]
[production.deploy.parameters]
stack_name = "ElectionLeafletsApp-production"
s3_bucket = "election-leaflets-deployment-artifacts-production-238416"
s3_prefix = "production"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"elctionleaflets\" dc-environment=\"production\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
# Using a "parameter_overrides" setting here would block using CI envvars, as only
# one overrides source is used and this source doesn't pass through shell interpolation.

[production.logs]
[production.logs.parameters]
stack_name = "ElectionLeafletsApp-production"
name = "ElectionLeafletsFunction"
region = "eu-west-2"

[production-public-access]
[production-public-access.deploy]
[production-public-access.deploy.parameters]
template = "public-access-template.yaml"
stack_name = "ElectionLeafletsPublicAccess-production"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"elctionleaflets\" dc-environment=\"production\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
# Using a "parameter_overrides" setting here would block using CI envvars, as only
# one overrides source is used and this source doesn't pass through shell interpolation.
