# This file and its quirks are documented here:
# https://github.com/aws/aws-sam-cli/blob/develop/docs/sam-config-docs.md
version = 0.1

####################################################################################
## NB: Don't insert a "default" profile in this file! ##############################
###### Only use named, per-environment profiles. ###################################
###### This will help guard against accidentally targetting the wrong environment. #
####################################################################################

[staging]

[staging.deploy]
[staging.deploy.parameters]
stack_name = "ElectionLeafletsApp-staging"
s3_bucket = "elctionleaflets-deployment-artifacts-staging-6jfsds0gj3f"
s3_prefix = "staging"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"elctionleaflets\" dc-environment=\"staging\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
# Using a "parameter_overrides" setting here would block using CI envvars, as only
# one overrides source is used and this source doesn't pass through shell interpolation.

[staging.logs]
[staging.logs.parameters]
stack_name = "ElectionLeafletsApp-staging"
name = "ElectionLeafletsFunction"
region = "eu-west-2"

[staging-public-access]
[staging-public-access.deploy]
[staging-public-access.deploy.parameters]
template = "public-access-template.yaml"
stack_name = "ElectionLeafletsPublicAccess-staging"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"elctionleaflets\" dc-environment=\"staging\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
# Using a "parameter_overrides" setting here would block using CI envvars, as only
# one overrides source is used and this source doesn't pass through shell interpolation.
