# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 23:06
from __future__ import unicode_literals
import requests

from django.db import migrations


def add_missing_people(apps, schema_editor):
    Leaflet = apps.get_model("leaflets", "Leaflet")
    Person = apps.get_model("people", "Person")
    for leaflet in Leaflet.objects.exclude(publisher_person_id=None):
        try:
            leaflet.publisher_person
        except Person.DoesNotExist:
            try:
                person = Person.objects.get(remote_id=leaflet.publisher_person_id)
            except Person.DoesNotExist:

                url = "https://candidates.democracyclub.org.uk/api/next/people/{}/".format(leaflet.publisher_person_id)
                ynr_person_data = requests.get(url).json()
                person = Person.objects.create(
                    remote_id=leaflet.publisher_person_id,
                    name=ynr_person_data["name"],
                )
            leaflet.publisher_person = person
            leaflet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20160403_1456'),
        ('people', '0002_import_ynr_people'),
    ]

    operations = [
        migrations.RunPython(add_missing_people, migrations.RunPython.noop)
    ]
