# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 14:56


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0001_initial"),
        ("constituencies", "0001_initial"),
        ("uk_political_parties", "0004_auto_20150322_2250"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyMemberships",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("membership_start", models.DateField()),
                ("membership_end", models.DateField(null=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uk_political_parties.Party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "remote_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                ("source_name", models.CharField(blank=True, max_length=100)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonConstituencies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "constituency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="constituencies.Constituency",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.Election",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.Person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="constituencies",
            field=models.ManyToManyField(
                through="people.PersonConstituencies",
                to="constituencies.Constituency",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="elections",
            field=models.ManyToManyField(to="elections.Election"),
        ),
        migrations.AddField(
            model_name="person",
            name="parties",
            field=models.ManyToManyField(
                through="people.PartyMemberships",
                to="uk_political_parties.Party",
            ),
        ),
        migrations.AddField(
            model_name="partymemberships",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="people.Person"
            ),
        ),
    ]
