# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-15 22:14


from django.db import migrations


def import_people(apps, _):
    Leaflet = apps.get_model("leaflets", "Leaflet")
    Person = apps.get_model("people", "Person")

    leaflets = Leaflet.objects.filter(
        ynr_person_id__isnull=False, publisher_person__isnull=True
    )

    for leaflet in leaflets:
        person, _ = Person.objects.get_or_create(
            remote_id=leaflet.ynr_person_id,
            source_name="YNR2017",
            defaults={
                "name": leaflet.ynr_person_name,
                "source_url": "https://candidates.democracyclub.org.uk/person/{}".format(
                    leaflet.ynr_person_id
                ),
            },
        )

        leaflet.publisher_person = person
        leaflet.save()


class Migration(migrations.Migration):
    dependencies = [
        ("leaflets", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(import_people),
    ]
