# Generated by Django 2.2.20 on 2021-04-25 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_import_ynr_people"),
        ("people", "0004_unique_remote_id"),
    ]

    operations = []
