# Generated by Django 4.2.15 on 2024-12-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_merge_20210425_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='constituencies',
        ),
        migrations.RemoveField(
            model_name='person',
            name='elections',
        ),
        migrations.RemoveField(
            model_name='person',
            name='parties',
        ),
        migrations.RemoveField(
            model_name='personconstituencies',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='personconstituencies',
            name='election',
        ),
        migrations.RemoveField(
            model_name='personconstituencies',
            name='person',
        ),
        migrations.DeleteModel(
            name='PartyMemberships',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonConstituencies',
        ),
    ]
