# Generated by Django 4.2.16 on 2024-12-09 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_merge_20210425_1928"),
        ("leaflets", "0008_move_publisher_person_data_to_ynr_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="parties",
        ),
        migrations.DeleteModel(
            name="PartyMemberships",
        ),
    ]
