# Generated by Django 4.2.16 on 2024-12-09 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0006_remove_person_parties_delete_partymemberships"),
        ("leaflets", "0009_remove_leaflet_publisher_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personconstituencies",
            name="constituency",
        ),
        migrations.RemoveField(
            model_name="personconstituencies",
            name="election",
        ),
        migrations.RemoveField(
            model_name="personconstituencies",
            name="person",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="PersonConstituencies",
        ),
    ]
