# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-30 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflets', '0002_leaflet_publisher_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafletimage',
            name='exif_data',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='leafletimage',
            name='orientation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horizontal (normal)'), (2, 'Mirror horizontal'), (3, 'Rotate 180'), (4, 'Mirror vertical'), (5, 'Mirror horizontal and rotate 270 CW'), (6, 'Rotate 90 CW'), (7, 'Mirror horizontal and rotate 90 CW'), (8, 'Rotate 270 CW')], default=1),
        ),
    ]
