# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-07 21:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaflets", "0003_Add orientation and exif data"),
    ]

    operations = [
        migrations.RemoveField(model_name="leafletimage", name="image_text",),
    ]
