# Generated by Django 2.2.27 on 2024-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflets', '0004_auto_20210502_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leafletimage',
            options={'ordering': ['pk', 'image_type']},
        ),
        migrations.AddField(
            model_name='leaflet',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaflet',
            name='status',
            field=models.CharField(blank=True, choices=[('live', 'Live'), ('draft', 'Draft'), ('removed', 'Removed')], default='draft', max_length=255, null=True),
        ),
    ]
