# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-15 16:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaflets", "0005_add_ynr_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaflet",
            name="ynr_party_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="leaflet",
            name="ynr_person_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
