# Generated by Django 2.2.20 on 2021-05-02 12:55

from django.db import migrations


def move_party_model_to_ynr_party(apps, schema_editor):
    Leaflet = apps.get_model("leaflets", "Leaflet")
    qs = Leaflet.objects.exclude(publisher_party_id=None).select_related(
        "publisher_party"
    )
    for leaflet in qs:
        # YNR uses `party:` style IDs rather than the proper 'PP*` IDs.
        # this is something to fix later: for now we want everything to be
        # the same
        leaflet.ynr_party_id = leaflet.publisher_party_id.replace(
            "PP", "party:"
        )
        leaflet.ynr_party_name = leaflet.publisher_party.party_name
        leaflet.save()


class Migration(migrations.Migration):
    dependencies = [
        ("leaflets", "0005_auto_20240617_1459"),
    ]

    operations = [
        migrations.RunPython(
            move_party_model_to_ynr_party, migrations.RunPython.noop
        ),
    ]
