# Generated by Django 2.2.20 on 2021-04-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaflets', '0007_add_ynr_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaflet',
            name='location',
        ),
    ]
