# Generated by Django 4.2.15 on 2024-12-07 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leaflets", "0008_move_publisher_person_data_to_ynr_id"),
        ("people", "0002_import_ynr_people"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaflet",
            name="publisher_person",
        ),
    ]
