# Generated by Django 4.2.16 on 2024-12-09 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leaflets", "0009_remove_leaflet_publisher_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaflet",
            name="constituency",
        ),
    ]
