# Generated by Django 4.2.15 on 2024-12-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaflets', '0009_remove_leaflet_publisher_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaflet',
            name='constituency',
        ),
    ]
