# Generated by Django 4.2.17 on 2024-12-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaflets", "0012_leaflet_nuts1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaflet",
            name="nuts1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UKC", "North East"),
                    ("UKD", "North West"),
                    ("UKE", "Yorkshire and the Humber"),
                    ("UKF", "East Midlands"),
                    ("UKG", "West Midlands"),
                    ("UKH", "East of England"),
                    ("UKI", "London"),
                    ("UKJ", "South East"),
                    ("UKK", "South West"),
                    ("UKL", "Wales"),
                    ("UKM", "Scotland"),
                    ("UKN", "Northern Ireland"),
                ],
                max_length=3,
            ),
        ),
    ]
