# Generated by Django 4.2.17 on 2025-01-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaflets", "0013_alter_leaflet_nuts1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaflet",
            name="ballots",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="leaflet",
            name="people",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="leaflet",
            name="person_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
