# Generated by Django 4.2.17 on 2025-01-20 15:09

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from leaflets.managers import (
    NAME_SEARCH_TRIGGER_SQL,
    POPULATE_NAME_SEARCH_COLUMN_SQL,
)


class Migration(migrations.Migration):
    dependencies = [
        (
            "leaflets",
            "0014_alter_leaflet_ballots_alter_leaflet_people_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="leaflet",
            name="name_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(default=""),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="leaflet",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_search_vector"], name="name_vector_search_index"
            ),
        ),
        migrations.RunSQL(
            POPULATE_NAME_SEARCH_COLUMN_SQL, migrations.RunSQL.noop
        ),
        migrations.RunSQL(NAME_SEARCH_TRIGGER_SQL, migrations.RunSQL.noop),
    ]
