# Generated by Django 4.2.17 on 2025-01-29 15:06

from django.db import migrations


def convert_person_ids_strings_to_ints(apps, schema_editor):
    Leaflet = apps.get_model("leaflets", "Leaflet")

    for obj in Leaflet.objects.all():
        if obj.person_ids:
            obj.person_ids = [int(item) for item in obj.person_ids]
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("leaflets", "0015_leaflet_name_search_vector_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_person_ids_strings_to_ints),
    ]
