# Generated by Django 5.2.15 on 2026-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaflets", "0016_convert_ynr_ids_to_int"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaflet",
            name="ynr_party_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
            preserve_default=False,
        ),
    ]
