# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: boffbowsh/circleci-python-geos:2.7.14-3.5.0
        environment:
          RUNNER: circleci

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: mdillon/postgis:9.6
        environment:
          POSTGRES_USER: postgres
          PGUSER: postgres
          POSTGRES_DB: electionleaflets_test
          POSTGRES_PASSWORD:
      - image: redis

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install

      - save_cache:
          key: v2-dependencies-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            pipenv run flake8 electionleaflets
            pipenv run python manage.py test
            pipenv run python manage.py harvest

      - store_artifacts:
          path: test-reports
          destination: test-reports
