# This file and its quirks are documented here:
# https://github.com/aws/aws-sam-cli/blob/develop/docs/sam-config-docs.md
version = 0.1

####################################################################################
## NB: Don't insert a "default" profile in this file! ##############################
###### Only use named, per-environment profiles. ###################################
###### This will help guard against accidentally targetting the wrong environment. #
####################################################################################

[production]

[production.deploy]
[production.deploy.parameters]
stack_name = "ElectionLeafletsThumbs-production"
s3_bucket = "election-leaflets-deployment-artifacts-production-us-238416"
s3_prefix = "staging"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
tags = "dc-product=\"elctionleaflets\" dc-environment=\"production\""
progressbar = false
fail_on_empty_changeset = false
force_upload = true
# Using a "parameter_overrides" setting here would block using CI envvars, as only
# one overrides source is used and this source doesn't pass through shell interpolation.

[staging.logs]
[staging.logs.parameters]
stack_name = "ElectionLeafletsThumbs-production"
name = "ThumbsFunction"
region = "eu-west-2"
