# Generated by Django 4.2.16 on 2024-12-09 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("constituencies", "0001_initial"),
        ("people", "0007_remove_personconstituencies_constituency_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Constituency",
        ),
    ]
