# Generated by Django 4.2.15 on 2024-12-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaflets', '0010_remove_leaflet_constituency'),
        ('constituencies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constituency',
        ),
    ]
