# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 14:57


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "country_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("iso", models.CharField(max_length=6)),
                ("name", models.CharField(max_length=240)),
                ("iso3", models.CharField(blank=True, max_length=9)),
            ],
            options={
                "db_table": "country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="EmailAlert",
            fields=[
                (
                    "email_alert_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=150)),
                ("frequency_hours", models.IntegerField()),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(max_length=150)),
                ("parent_id", models.IntegerField()),
                ("activated", models.IntegerField(blank=True, null=True)),
                ("confirm_id", models.CharField(max_length=300)),
                ("title", models.CharField(max_length=765)),
            ],
            options={
                "db_table": "email_alert",
                "verbose_name_plural": "Email alerts",
            },
        ),
        migrations.CreateModel(
            name="EmailQue",
            fields=[
                (
                    "email_que_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=765)),
                ("email", models.CharField(max_length=765)),
                ("postcode", models.CharField(max_length=60)),
                ("delivery_date", models.DateTimeField()),
            ],
            options={"db_table": "email_que",},
        ),
        migrations.CreateModel(
            name="ImageQue",
            fields=[
                (
                    "image_que_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("upload_key", models.CharField(max_length=765)),
                ("name", models.CharField(blank=True, max_length=300)),
                ("email", models.CharField(blank=True, max_length=300)),
                ("image_key", models.CharField(blank=True, max_length=765)),
                ("uploaded_date", models.DateTimeField()),
            ],
            options={"db_table": "image_que",},
        ),
        migrations.CreateModel(
            name="ImageQueSeq",
            fields=[
                (
                    "sequence",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
            options={"db_table": "image_que_seq",},
        ),
    ]
