# Generated by Django 4.2.25 on 2025-10-15 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="EmailAlert",
        ),
        migrations.DeleteModel(
            name="EmailQue",
        ),
        migrations.DeleteModel(
            name="ImageQue",
        ),
        migrations.DeleteModel(
            name="ImageQueSeq",
        ),
    ]
