[project]
name = "thumbs"
version = "0.0.0"
description = "Lambda function that produces thumbnails from raw leaflets"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "django==5.2.7",
    "pillow-heif==0.22.0",
    "pillow==11.3.0",
    "sentry-sdk==2.20.0",
    "sorl-thumbnail==12.11.0",
]

[tool.uv]
package = false
required-version = "==0.8.*"
