[project]
name = "thumbs"
version = "0.0.0"
description = "Lambda function that produces thumbnails from raw leaflets"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow===10.4.0",
    "sorl-thumbnail===12.11.0",
]

[tool.uv]
package = false
