AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "EC API app: Lambda, API Gateway"

Globals:
  Function:
    Timeout: 30
  Api:
    BinaryMediaTypes:
      - "*/*"
Parameters:
  DCEnvironment:
    Default: DC_ENVIRONMENT
    Description: "The DC_ENVIRONMENT environment variable passed to the app."
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  ThumbsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ElectionLeafletsThumbs-${DCEnvironment}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/ElectionLeafletsLambdaExecutionRole"
      CodeUri: .
      Handler: handler.handle
      Runtime: python3.12
      MemorySize: 1024
